#!/usr/bin/env ruby

# Script to create a new Ticket Poker item given the ID of a team
# and the external URL (or title) of the ticket/story to estimate

require 'json'
require 'uri'
require 'net/http'

TICKET_POKER_TEAM_ID = '[insert your team_id here]'

ticket_url = ARGV.shift

def create_ticket(url)
  puts TicketPoker.new(team_id: TICKET_POKER_TEAM_ID).create(url)
end

########################################

class TicketPoker
  attr_reader :team_id

  URL = 'https://ticket-poker.herokuapp.com/api/tickets'

  def initialize(team_id:)
    @team_id = team_id
  end

  def create(url)
    data = {team_id: team_id, ticket_url: url}

    uri = URI(URL)
    https = Net::HTTP.new(uri.host, uri.port)
    https.use_ssl = true
    request = Net::HTTP::Post.new(uri.path)
    request['Accept']         = 'application/json'
    request['Content-Type']   = 'application/json'

    request.body = data.to_json

    rtn = https.request(request)
    JSON.parse(rtn.body).fetch('url')
  end
end

create_ticket(ticket_url)

